---
- hosts: all
  become: true
  tasks:
   - name: Update repo index, install apache/php
     package:
      name:
         - "{{ apache_package }}"
         - "{{ php_package }}"
      state: latest
      update_cache: yes
