---
- hosts: all
  become: true
  tasks:
   - name: Update repository index
     apt:
       update_cache: yes
   - name: Install Apache
     apt:
       name: apache2
   - name: add php sup
     apt:
       name: libapache2-mod-php
